# Generated by Django 5.2.6 on 2025-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABC_Company',
            fields=[
                ('Car_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Car_Model', models.CharField(max_length=30)),
                ('Number_of_cars_sold', models.IntegerField()),
                ('Year_Produced', models.DateField()),
                ('Annual_Revenue', models.IntegerField()),
            ],
        ),
    ]
